version: '3.5'

services:
    api:
        build: .
        environment:
            - NODE_ENV=production
            - DB_URL=postgresql://db:5432/FMDB?user=admin&password=fastmoneyapi
        ports:
            - '3000:3000'
        depends_on:
            - db
        networks:
            - api
        deploy:
            resources:
                limits:
                    cpus: '0.6'
                    memory: '200MB'
    db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=fastmoneyapi
            - POSTGRES_USER=admin
            - POSTGRES_DB=FMDB
        ports:
            - '5432:5432'
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/script.sql
        networks:
            - api
        deploy:
            resources:
                limits:
                    cpus: '0.13'
                    memory: '140MB'
networks:
    api:
        driver: bridge
