version: '3.5'

services:
    api:
        build: .
        hostname: api
        environment:
            - DB_HOSTNAME=db
        ports:
            - '3000:3000'
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: '0.6'
                    memory: '200MB'
    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_PASSWORD=fastmoneyapi
            - POSTGRES_USER=admin
            - POSTGRES_DB=FMDB
        ports:
            - '5432:5432'
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/script.sql
        deploy:
            resources:
                limits:
                    cpus: '0.13'
                    memory: '140MB'
networks:
    default:
        driver: bridge
        name: fast-money
